_wandb:
    value:
        cli_version: 0.19.0
        m: []
        python_version: 3.9.6
        t:
            "1":
                - 5
                - 53
                - 55
            "2":
                - 5
                - 53
                - 55
            "3":
                - 2
                - 13
                - 23
                - 24
                - 55
            "4": 3.9.6
            "5": 0.19.0
            "8":
                - 1
                - 5
            "12": 0.19.0
            "13": darwin-x86_64
